Working!

diff --git a/recipes/rsw-single-server/templates/server-side-justfile b/recipes/rsw-single-server/templates/server-side-justfile
--- a/recipes/rsw-single-server/templates/server-side-justfile
+++ b/recipes/rsw-single-server/templates/server-side-justfile
@@ -1,6 +1,7 @@
 set dotenv-load
 
 SERVER_IP_ADDRESS := env_var("SERVER_IP_ADDRESS")
+SERVER_PUBLIC_DNS := env_var("SERVER_PUBLIC_DNS")
 RSW_LICENSE := env_var("RSW_LICENSE")
 
 R_VERSION := env_var_or_default("R_VERSION", "4.1.2")
@@ -30,6 +31,9 @@ build-rsw:
     just install-vscode
     sudo cp -r /etc/rstudio /etc/rstudio-original-conf-files
 
+    # Set up SSL
+    just ssl-self-sign-cert
+    
     # Set up config files
     just set-rserver-conf
     just set-launcher-conf
@@ -37,7 +41,10 @@ build-rsw:
 
     # Restart
     sudo rstudio-server restart
-    sudo rstudio-launcher restart
+
+    # For some reason sudo rstudio-launcher restart is throwing an error.  
+    # Use the || operator so that justfile does not think the recipe failed.
+    sudo rstudio-launcher restart || echo
 
 # -----------------------------------------------------------------------------
 # Install
@@ -47,7 +54,6 @@ install-linux-tools:
     sudo apt-get install -y tree
     sudo apt-get install -y bat
     sudo apt-get install -y gdebi-core
-    sudo apt-get install -y nginx
 
 install-rsw:
     curl -O https://download2.rstudio.org/server/bionic/amd64/rstudio-workbench-2022.02.3-492.pro3-amd64.deb
@@ -92,9 +98,9 @@ symlink-r:
     sudo ln -s /opt/R/{{R_VERSION}}/bin/R /usr/local/bin/R
     sudo ln -s /opt/R/{{R_VERSION}}/bin/Rscript /usr/local/bin/Rscript
 
-get-ssl-cert:
-    sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/nginx.key -out /etc/ssl/nginx.crt
-    sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt 
+ssl-self-sign-cert:
+    just set-ssl-san-cnf
+    sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/server.key -out /etc/ssl/server.crt -config /etc/ssl/san.cnf
 
 # -----------------------------------------------------------------------------
 # Configuration files
@@ -103,10 +109,15 @@ get-ssl-cert:
 set-rserver-conf:
     #!/bin/bash
     sudo bash -c 'cat <<EOF > /etc/rstudio/rserver.conf
-    www-port=8787
+    www-port=443
     admin-enabled=1
     admin-group=sam
     server-health-check-enabled=1
+
+    # SSL
+    ssl-enabled=1
+    ssl-certificate=/etc/ssl/server.crt
+    ssl-certificate-key=/etc/ssl/server.key
 
     # Launcher Config
     launcher-address=127.0.0.1
@@ -143,68 +154,30 @@ set-vscode-extensions-conf:
     EOF'
 
 # -----------------------------------------------------------------------------
-# Nginx and SSL
+# SSL
 # -----------------------------------------------------------------------------
 
-set-nginx-snippet-self-signed-conf:
+set-ssl-san-cnf:
     #!/bin/bash
-    sudo bash -c 'cat <<EOF > /etc/nginx/snippets/self-signed.conf
-    ssl_certificate /etc/ssl/nginx.crt; ssl_certificate_key /etc/ssl/nginx.key; 
-    EOF'
-
-set-nginx-snippet-ssl-params-conf:
-    #!/bin/bash
-    sudo bash -c 'cat <<EOF > /etc/nginx/snippets/ssl-params.conf
-    ssl_certificate /etc/ssl/nginx.crt; ssl_certificate_key /etc/ssl/nginx.key; 
-    EOF'
-
-set-nginx-conf:
-    #!/bin/bash
-    sudo bash -c 'cat <<EOF > /etc/rstudio/vscode.extensions.conf 
-    user www-data;
-    worker_processes auto;
-    pid /run/nginx.pid;
-    include /etc/nginx/modules-enabled/*.conf;
-
-    events {
-        worker_connections 768;
-    }
-
-    http {
-
-    # Support proxying of web-socket connections
-        map $http_upgrade $connection_upgrade {
-            default upgrade;
-            ''      close;
-        }
-    
-        server {
-            listen 80;
-            server_name {{SERVER_IP_ADDRESS}} www.{{SERVER_IP_ADDRESS}};
-
-            # -------------------------------------------------------------------------
-            # RSW
-            # -------------------------------------------------------------------------
-            location /rstudio/ {
-                # Needed only for a custom path prefix of /rstudio
-                rewrite ^/rstudio(.*)$ /$1 break;
-
-                # Use http here when ssl-enabled=0 is set in rserver.conf
-                proxy_pass http://{{SERVER_IP_ADDRESS}}:8787;
-
-                proxy_http_version 1.1;
-                proxy_set_header Upgrade $http_upgrade;
-                proxy_set_header Connection $connection_upgrade;
-                proxy_read_timeout 20d;
-
-                # Not needed if www-root-path is set in rserver.conf
-                proxy_set_header X-RStudio-Root-Path /rstudio;
-
-                # Optionally, use an explicit hostname and omit the port if using 80/443
-                proxy_set_header Host $host:$server_port;
-            }
-        }
-    }
+    sudo bash -c 'cat <<EOF > /etc/ssl/san.cnf
+    [req]
+    default_bits  = 2048
+    distinguished_name = req_distinguished_name
+    req_extensions = req_ext
+    x509_extensions = v3_req
+    prompt = no
+    [req_distinguished_name]
+    countryName = XX
+    stateOrProvinceName = N/A
+    localityName = N/A
+    organizationName = Self-signed certificate
+    commonName = {{SERVER_PUBLIC_DNS}}
+    [req_ext]
+    subjectAltName = @alt_names
+    [v3_req]
+    subjectAltName = @alt_names
+    [alt_names]
+    IP.1 = {{SERVER_IP_ADDRESS}}
     EOF'
 
 # -----------------------------------------------------------------------------
@@ -227,6 +200,9 @@ status:
 logs:
     sudo tail /var/log/rstudio/rstudio-server/rserver.log
 
+logs-watch:
+    sudo tail -f /var/log/rstudio/rstudio-server/rserver.log
+
 edit:
     sudo vim /etc/rstudio/rserver.conf
 
@@ -235,3 +211,4 @@ edit-database:
 
 edit-load-balancer:
     sudo vim /etc/rstudio/load-balancer
+
